import type { EvaluationSummary } from "@/lib/types";

type Props = {
  summary: EvaluationSummary | null;
  onLoad: () => void;
  busy: boolean;
};

function percent(value: number | undefined) {
  return value === undefined ? "—" : `${Math.round(value * 100)}%`;
}

export function EvaluationDashboard({ summary, onLoad, busy }: Props) {
  return (
    <section className="panel evaluation-panel" aria-labelledby="evaluation-title">
      <div className="panel-heading">
        <div>
          <p className="eyebrow">05 · Frozen benchmark</p>
          <h2 id="evaluation-title">Model and policy evidence</h2>
        </div>
        <span className={`status-chip ${summary?.status === "passed" ? "trusted" : "idle"}`}>
          {summary?.status ?? "Not loaded"}
        </span>
      </div>
      {!summary ? (
        <div className="evaluation-empty">
          <p className="supporting-copy">
            Load the immutable golden-set result generated by the grouped training, calibration, and
            time-forward evaluation pipeline.
          </p>
          <button className="button secondary" type="button" onClick={onLoad} disabled={busy}>
            Load benchmark results
          </button>
        </div>
      ) : (
        <>
          <div className="metric-grid">
            <article><span>Violation recall</span><strong>{percent(summary.metrics.violation_recall)}</strong></article>
            <article><span>False step-up</span><strong>{percent(summary.metrics.false_step_up_rate)}</strong></article>
            <article><span>False decline</span><strong>{percent(summary.metrics.false_decline_rate)}</strong></article>
            <article><span>PR-AUC</span><strong>{percent(summary.metrics.pr_auc)}</strong></article>
            <article><span>Calibration error</span><strong>{percent(summary.metrics.expected_calibration_error)}</strong></article>
            <article><span>Decision p95</span><strong>{summary.latency_ms.p95?.toFixed(2) ?? "—"} ms</strong></article>
          </div>
          <div className="benchmark-meta">
            <code>{summary.dataset_version}</code>
            <span>→</span>
            <code>{summary.model_version}</code>
            <span>{Object.keys(summary.attack_families).length} attack families</span>
          </div>
        </>
      )}
    </section>
  );
}

