/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mandates/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interpret Route */
        post: operations["interpret_route_v1_mandates_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mandates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Route */
        post: operations["confirm_route_v1_mandates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mandates/{mandate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mandate Route */
        get: operations["mandate_route_v1_mandates__mandate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mandates/{mandate_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Route */
        post: operations["revoke_route_v1_mandates__mandate_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Route */
        post: operations["evaluate_route_v1_decisions_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/{decision_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Route */
        post: operations["resolve_route_v1_decisions__decision_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Route */
        get: operations["audit_route_v1_sessions__session_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation Route */
        get: operations["evaluation_route_v1_evaluation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalPolicy */
        ApprovalPolicy: {
            /**
             * Allow Step Up
             * @default true
             */
            allow_step_up: boolean;
            /**
             * Allow Agent Override
             * @default false
             */
            allow_agent_override: boolean;
        };
        /** AuditEvent */
        AuditEvent: {
            /** Event Id */
            event_id: string;
            /** Session Id */
            session_id: string;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditTimeline */
        AuditTimeline: {
            /** Session Id */
            session_id: string;
            /** Events */
            events: components["schemas"]["AuditEvent"][];
        };
        /** CartEvidence */
        CartEvidence: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Cart Id */
            cart_id: string;
            /** Merchant Id */
            merchant_id: string;
            /** Merchant Category */
            merchant_category: string;
            /** Evidence Source */
            evidence_source: string;
            /** Evidence Trust */
            evidence_trust: string;
            /** Currency */
            currency: string;
            /** Total Amount Minor */
            total_amount_minor: number;
            /** Line Items */
            line_items: components["schemas"]["LineItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Reference */
            evidence_reference: string;
        };
        /** ConfirmMandateRequest */
        ConfirmMandateRequest: {
            proposal: components["schemas"]["MandateProposal-Input"];
            /** Confirmed */
            confirmed: boolean;
        };
        /** Constraint */
        Constraint: {
            /** Constraint Id */
            constraint_id: string;
            type: components["schemas"]["ConstraintType"];
            operator: components["schemas"]["Operator"];
            /** Value */
            value?: unknown | null;
            /** Amount Minor */
            amount_minor?: number | null;
            /** Currency */
            currency?: string | null;
            /** Source Span */
            source_span?: string | null;
        };
        /**
         * ConstraintType
         * @enum {string}
         */
        ConstraintType: "total_budget" | "currency" | "semantic_attribute" | "route" | "travel_dates" | "prohibited_item" | "prohibited_category" | "allowed_merchant" | "max_fulfillments";
        /** DecisionResponse */
        DecisionResponse: {
            /** Decision Id */
            decision_id: string;
            /** Mandate Id */
            mandate_id: string;
            /** Cart Id */
            cart_id: string;
            treatment: components["schemas"]["Treatment"];
            /** Risk Probability */
            risk_probability: number;
            /** Uncertainty Band */
            uncertainty_band: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Card Member Explanation */
            card_member_explanation: string;
            /** Reviewer Explanation */
            reviewer_explanation: string;
            /** Rule Results */
            rule_results: components["schemas"]["RuleResult"][];
            /** Semantic Results */
            semantic_results: components["schemas"]["SemanticResult"][];
            model_versions: components["schemas"]["ModelVersions"];
            /** Evidence References */
            evidence_references: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvaluateDecisionRequest */
        EvaluateDecisionRequest: {
            /** Mandate Id */
            mandate_id: string;
            cart: components["schemas"]["CartEvidence"];
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            /** Dataset Version */
            dataset_version: string;
            /** Model Version */
            model_version: string;
            /** Status */
            status: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Attack Families */
            attack_families: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Latency Ms */
            latency_ms: {
                [key: string]: number;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterpretMandateRequest */
        InterpretMandateRequest: {
            /** Objective Text */
            objective_text: string;
            /**
             * Principal Id
             * @default cm_demo_001
             */
            principal_id: string;
            /**
             * Agent Id
             * @default agent_demo_travel
             */
            agent_id: string;
            /**
             * Market Timezone
             * @default Asia/Singapore
             */
            market_timezone: string;
        };
        /** InterpretationResponse */
        InterpretationResponse: {
            proposal: components["schemas"]["MandateProposal-Output"];
            /** Warnings */
            warnings?: string[];
            /**
             * Requires Confirmation
             * @default true
             */
            requires_confirmation: boolean;
            /**
             * Interpreter Version
             * @default deterministic-v1
             */
            interpreter_version: string;
        };
        /** LineItem */
        LineItem: {
            /** Line Item Id */
            line_item_id: string;
            /** Description */
            description: string;
            /** Quantity */
            quantity: number;
            /** Amount Minor */
            amount_minor: number;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /** Mandate */
        Mandate: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mandate Id */
            mandate_id: string;
            /**
             * Mandate Version
             * @default 1
             */
            mandate_version: number;
            /** Principal Id */
            principal_id: string;
            /** Agent Id */
            agent_id: string;
            /** Objective Text */
            objective_text: string;
            /** Constraints */
            constraints: components["schemas"]["Constraint"][];
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Max Fulfillments
             * @default 1
             */
            max_fulfillments: number;
            approval_policy?: components["schemas"]["ApprovalPolicy"];
            /** Authorization Reference */
            authorization_reference: string;
            /**
             * Authenticated At
             * Format: date-time
             */
            authenticated_at: string;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Superseded Mandate Reference */
            superseded_mandate_reference?: string | null;
        };
        /** MandateProposal */
        "MandateProposal-Input": {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mandate Id */
            mandate_id: string;
            /**
             * Mandate Version
             * @default 1
             */
            mandate_version: number;
            /** Principal Id */
            principal_id: string;
            /** Agent Id */
            agent_id: string;
            /** Objective Text */
            objective_text: string;
            /** Constraints */
            constraints: components["schemas"]["Constraint"][];
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Max Fulfillments
             * @default 1
             */
            max_fulfillments: number;
            approval_policy?: components["schemas"]["ApprovalPolicy"];
        };
        /** MandateProposal */
        "MandateProposal-Output": {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Mandate Id */
            mandate_id: string;
            /**
             * Mandate Version
             * @default 1
             */
            mandate_version: number;
            /** Principal Id */
            principal_id: string;
            /** Agent Id */
            agent_id: string;
            /** Objective Text */
            objective_text: string;
            /** Constraints */
            constraints: components["schemas"]["Constraint"][];
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Max Fulfillments
             * @default 1
             */
            max_fulfillments: number;
            approval_policy?: components["schemas"]["ApprovalPolicy"];
        };
        /** MandateState */
        MandateState: {
            /** Mandate Id */
            mandate_id: string;
            /** Current Version */
            current_version: number;
            /** Status */
            status: string;
            /**
             * Fulfilled Amount Minor
             * @default 0
             */
            fulfilled_amount_minor: number;
            /**
             * Fulfillment Count
             * @default 0
             */
            fulfillment_count: number;
            /** Prior Transaction Ids */
            prior_transaction_ids?: string[];
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
        };
        /** MandateView */
        MandateView: {
            mandate: components["schemas"]["Mandate"];
            state: components["schemas"]["MandateState"];
        };
        /** ModelVersions */
        ModelVersions: {
            /** Semantic */
            semantic: string;
            /** Catboost */
            catboost?: string | null;
            /** Tabm */
            tabm?: string | null;
            /** Stacker */
            stacker?: string | null;
            /** Calibrator */
            calibrator?: string | null;
            /** Policy */
            policy: string;
            /** Features */
            features: string;
        };
        /**
         * Operator
         * @enum {string}
         */
        Operator: "lte" | "eq" | "required" | "prohibited" | "in";
        /**
         * ResolutionAction
         * @enum {string}
         */
        ResolutionAction: "APPROVE_ONCE" | "MODIFY_MANDATE" | "DECLINE";
        /** ResolutionResponse */
        ResolutionResponse: {
            /** Decision Id */
            decision_id: string;
            action: components["schemas"]["ResolutionAction"];
            /** Status */
            status: string;
            /** Mandate Id */
            mandate_id: string;
            /** New Mandate Id */
            new_mandate_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ResolveDecisionRequest */
        ResolveDecisionRequest: {
            action: components["schemas"]["ResolutionAction"];
            modified_proposal?: components["schemas"]["MandateProposal-Input"] | null;
        };
        /** RevocationResponse */
        RevocationResponse: {
            /** Mandate Id */
            mandate_id: string;
            /**
             * Status
             * @constant
             */
            status: "revoked";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RuleResult */
        RuleResult: {
            /** Rule Id */
            rule_id: string;
            status: components["schemas"]["RuleStatus"];
            /** Severity */
            severity: string;
            /** Observed Value */
            observed_value?: unknown | null;
            /** Expected Value */
            expected_value?: unknown | null;
            /** Evidence Reference */
            evidence_reference?: string | null;
            /** Reason Code */
            reason_code?: string | null;
        };
        /**
         * RuleStatus
         * @enum {string}
         */
        RuleStatus: "PASS" | "WARN" | "FAIL" | "NOT_EVALUABLE";
        /** SemanticResult */
        SemanticResult: {
            /** Constraint Id */
            constraint_id: string;
            /** Contradiction */
            contradiction: number;
            /** Entailment */
            entailment: number;
            /** Neutral */
            neutral: number;
            /** Evidence Reference */
            evidence_reference: string;
        };
        /**
         * Treatment
         * @enum {string}
         */
        Treatment: "APPROVE" | "STEP_UP" | "HOLD";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    interpret_route_v1_mandates_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretMandateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_route_v1_mandates_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMandateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mandate_route_v1_mandates__mandate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_route_v1_mandates__mandate_id__revoke_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                mandate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_route_v1_decisions_evaluate_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_route_v1_decisions__decision_id__resolve_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_route_v1_sessions__session_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_route_v1_evaluation_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSummary"];
                };
            };
        };
    };
}
